## 콘솔로그 색상
spring.output.ansi.enabled=always
## Log4J 설정
logging.level.org.springframework=info
logging.level.com.hugo83=debug
logging.level.org.springframework.security=trace
## DB 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mariadb://localhost:3326/nitflex
spring.datasource.username=nitflexuser
spring.datasource.password=nitflexp@ssw0rd
spring.datasource.mapper-locations=classpath:/mapper/**/*.xml

## 커스텀 API-Key properties 설정
tmdb-key=1aee496c40c67b8be663601b50f17fb8